services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: witple_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - witple_network
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: witple_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - witple_network
  # Backend (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: witple_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - redis
    volumes:
      - ./backend:/app
      - ~/.aws:/root/.aws:ro
    networks:
      - witple_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_API_BASE: ""
    container_name: witple_frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - API_INTERNAL_URL=http://backend:8000
      - NEXT_PUBLIC_API_BASE=/api
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - witple_network
volumes:
  postgres_data:
  redis_data:
networks:
  witple_network:
    driver: bridge