apiVersion: apps/v1
kind: Deployment
metadata:
  name: witple-frontend
  namespace: witple
  labels:
    app: witple-frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: witple-frontend
  template:
    metadata:
      labels:
        app: witple-frontend
    spec:
      containers:
      - name: witple-frontend
        image: ${ECR_REGISTRY}/witple-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: API_INTERNAL_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: API_INTERNAL_URL
        - name: NEXT_PUBLIC_API_BASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: NEXT_PUBLIC_API_BASE
        - name: NODE_ENV
          value: "production"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: NEXTAUTH_SECRET
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: GOOGLE_CLIENT_SECRET
        - name: NEXTAUTH_URL
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: NEXTAUTH_URL
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            secretKeyRef:
              name: oauth-secret
              key: NEXT_PUBLIC_API_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
